# Code generated by font_to_py.py.
# Font: heart.ttf Char set: T
# Cmd: font_to_py.py heart.ttf 14 -c T heart.py
version = '0.42'

def height():
    return 14

def baseline():
    return 14

def max_width():
    return 19

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 84

def max_ch():
    return 84

_font =\
b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'\
b'\x13\x00\x1e\x1e\x00\x3f\x3f\x00\x7f\xff\x80\x7f\xff\x80\x7f\xff'\
b'\x80\x7f\xff\x80\x7f\xff\x80\x3f\xff\x80\x3f\xff\x00\x1f\xfe\x00'\
b'\x0f\xfc\x00\x07\xf8\x00\x01\xf0\x00\x00\xc0\x00'

_index =\
b'\x00\x00\x10\x00\x3c\x00'

_mvfont = memoryview(_font)
_mvi = memoryview(_index)
ifb = lambda l : l[0] | (l[1] << 8)

def get_ch(ch):
    oc = ord(ch)
    ioff = 2 * (oc - 84 + 1) if oc >= 84 and oc <= 84 else 0
    doff = ifb(_mvi[ioff : ])
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 14
    return _mvfont[doff + 2:next_offs], 14, width


