# Code generated by font_to_py.py.
# Font: heart.ttf Char set: T
# Cmd: font_to_py.py heart.ttf 10 -c T heart.py
version = '0.42'

def height():
    return 9

def baseline():
    return 9

def max_width():
    return 13

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 84

def max_ch():
    return 84

_font =\
b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0d\x00\x38\xe0\x7d'\
b'\xf0\x7f\xf0\x7f\xf0\x7f\xf0\x3f\xe0\x1f\xc0\x0f\x80\x06\x00'

_index =\
b'\x00\x00\x0b\x00\x1f\x00'

_mvfont = memoryview(_font)
_mvi = memoryview(_index)
ifb = lambda l : l[0] | (l[1] << 8)

def get_ch(ch):
    oc = ord(ch)
    ioff = 2 * (oc - 84 + 1) if oc >= 84 and oc <= 84 else 0
    doff = ifb(_mvi[ioff : ])
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 9
    return _mvfont[doff + 2:next_offs], 9, width



