# Code generated by font_to_py.py.
# Font: heart.ttf Char set: T
# Cmd: font_to_py.py heart.ttf 12 -c T heart.py
version = '0.42'

def height():
    return 11

def baseline():
    return 11

def max_width():
    return 16

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 84

def max_ch():
    return 84

_font =\
b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x1c'\
b'\x78\x3e\xfc\x7f\xfc\x7f\xfc\x7f\xfc\x7f\xfc\x3f\xf8\x1f\xf8\x0f'\
b'\xf0\x07\xc0\x01\x80'

_index =\
b'\x00\x00\x0d\x00\x25\x00'

_mvfont = memoryview(_font)
_mvi = memoryview(_index)
ifb = lambda l : l[0] | (l[1] << 8)

def get_ch(ch):
    oc = ord(ch)
    ioff = 2 * (oc - 84 + 1) if oc >= 84 and oc <= 84 else 0
    doff = ifb(_mvi[ioff : ])
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 11
    return _mvfont[doff + 2:next_offs], 11, width


